### ISSUE TITLE
Module build error : failed to find 'basscss-border-colors'

### ISSUE THREAD

**Issue by midroid** [rangle/batarangle#107]
While trying to build the extension:
batarangle/webpack error?
After npm run build -> comes this error

ERROR in ./~/css-loader!./~/postcss-loader!./styles/app.css
Module build failed: Error: /home/ubuntu/workspace/batarangle/styles/app.css:2:1: Failed to find 'basscss-border-colors' from /home/ubuntu/workspace/batarangle
    in [ 
        /home/ubuntu/workspace/batarangle/styles
    ]
    at /home/ubuntu/workspace/batarangle/styles/app.css:2:1
    at resolveFilename (/home/ubuntu/workspace/batarangle/node_modules/postcss-import/index.js:532:11)
    at readAtImport (/home/ubuntu/workspace/batarangle/node_modules/postcss-import/index.js:288:26)
    at transformAtImport (/home/ubuntu/workspace/batarangle/node_modules/postcss-import/index.js:155:14)
    at Object.tryCatch [as try] (/home/ubuntu/workspace/batarangle/node_modules/postcss-import/node_modules/postcss-message-helpers/index.js:53:12)
    at /home/ubuntu/workspace/batarangle/node_modules/postcss-import/index.js:154:23
    at Array.map (native)
    at parseStyles (/home/ubuntu/workspace/batarangle/node_modules/postcss-import/index.js:153:31)
    at /home/ubuntu/workspace/batarangle/node_modules/postcss-import/index.js:83:30
    at LazyResult.run (/home/ubuntu/workspace/batarangle/node_modules/postcss-loader/node_modules/postcss/lib/lazy-result.js:206:20)
    at /home/ubuntu/workspace/batarangle/node_modules/postcss-loader/node_modules/postcss/lib/lazy-result.js:120:37
    at LazyResult.asyncTick (/home/ubuntu/workspace/batarangle/node_modules/postcss-loader/node_modules/postcss/lib/lazy-result.js:134:15)
    at processing.Promise.then._this2.processed (/home/ubuntu/workspace/batarangle/node_modules/postcss-loader/node_modules/postcss/lib/lazy-result.js:160:20)
    at LazyResult.async (/home/ubuntu/workspace/batarangle/node_modules/postcss-loader/node_modules/postcss/lib/lazy-result.js:157:27)
    at LazyResult.then (/home/ubuntu/workspace/batarangle/node_modules/postcss-loader/node_modules/postcss/lib/lazy-result.js:79:21)
    at Object.module.exports (/home/ubuntu/workspace/batarangle/node_modules/postcss-loader/index.js:47:32)
 @ ./~/style-loader!./~/css-loader!./~/postcss-loader!./styles/app.css 4:14-116

**Comment by sumitarora** [comment]
@midroid Can you let me know the version of `NPM` you are using? The issue only occurs in `NPM` version less than `3.x.x`. The application should build fine with the version mentioned in [Readme](https://github.com/rangle/batarangle/blob/master/README.md) or the latest version of `NPM`.

**Comment by kustov-vitalik** [comment]
I have the same error.
Node v4.2.5
NPM 3.5.3

ERROR in ./~/css-loader!./~/postcss-loader!./styles/app.css
Module build failed: Error: C:\xampp\htdocs\batarangle-master\styles\app.css:2:1: Failed to find 'basscss-border-colors' from C:\xampp\htdocs\batarangle-master
    in [
        C:\xampp\htdocs\batarangle-master\styles
    ]
    at C:\xampp\htdocs\batarangle-master\styles\app.css:2:1
    at resolveFilename (C:\xampp\htdocs\batarangle-master\node_modules\postcss-import\index.js:532:11)
    at readAtImport (C:\xampp\htdocs\batarangle-master\node_modules\postcss-import\index.js:288:26)
    at transformAtImport (C:\xampp\htdocs\batarangle-master\node_modules\postcss-import\index.js:155:14)
    at Object.tryCatch [as try] (C:\xampp\htdocs\batarangle-master\node_modules\postcss-import\node_modules\postcss-message-helpers\index.js:53:12)
    at C:\xampp\htdocs\batarangle-master\node_modules\postcss-import\index.js:154:23
    at Array.map (native)
    at parseStyles (C:\xampp\htdocs\batarangle-master\node_modules\postcss-import\index.js:153:31)
    at C:\xampp\htdocs\batarangle-master\node_modules\postcss-import\index.js:83:30
    at LazyResult.run (C:\xampp\htdocs\batarangle-master\node_modules\postcss-loader\node_modules\postcss\lib\lazy-result.js:206:20)
    at C:\xampp\htdocs\batarangle-master\node_modules\postcss-loader\node_modules\postcss\lib\lazy-result.js:120:37
    at LazyResult.asyncTick (C:\xampp\htdocs\batarangle-master\node_modules\postcss-loader\node_modules\postcss\lib\lazy-result.js:134:15)
    at processing.Promise.then._this2.processed (C:\xampp\htdocs\batarangle-master\node_modules\postcss-loader\node_modules\postcss\lib\lazy-result.js:160:20)
    at LazyResult.async (C:\xampp\htdocs\batarangle-master\node_modules\postcss-loader\node_modules\postcss\lib\lazy-result.js:157:27)
    at LazyResult.then (C:\xampp\htdocs\batarangle-master\node_modules\postcss-loader\node_modules\postcss\lib\lazy-result.js:79:21)
    at Object.module.exports (C:\xampp\htdocs\batarangle-master\node_modules\postcss-loader\index.js:47:32)
 @ ./~/style-loader!./~/css-loader!./~/postcss-loader!./styles/app.css 4:14-116

**Comment by midroid** [comment]
@sumitarora: Thanks,
With npm 3.5.3 and node v4.2.4, did it

**Comment by sumitarora** [comment]
@midroid good 

@kustov-vitalik can you check the configurations again do a clean install and check the build ?

**Comment by sumitarora** [comment]
@kustov-vitalik are you still having this issue ?

**Comment by sumitarora** [comment]
Node and NPM Version Issue
